# Generated by Django 3.0.6 on 2020-05-23 07:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200523_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='Users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='Users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='Users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='Users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='Users',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='Users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='Users',
            name='username',
        ),
        migrations.AddField(
            model_name='Users',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
