# Generated by Django 3.0.6 on 2020-05-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200523_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
