# Generated by Django 3.0.6 on 2020-05-23 07:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0002_auto_20160226_1747'),
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0007_auto_20200523_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userss',
        ),
    ]
