# Generated by Django 3.0.6 on 2020-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200526_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timein', models.TimeField(blank=True, null=True)),
                ('timeout', models.TimeField(blank=True, null=True)),
                ('user', models.ManyToManyField(to='api.Userss')),
            ],
        ),
    ]
