# Generated by Django 3.0.6 on 2020-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200527_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timein',
            field=models.TimeField(null=True),
        ),
    ]
