# Generated by Django 3.0.6 on 2020-05-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200528_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timein',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
